from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field


class Movie(SQLModel, table=True):
    """
    Represent a movie stored in the shared movie catalog.

    Movie information is stored once and can be referenced
    by multiple users through the UserMovie model.
    """

    __tablename__ = "movies"

    # Prevent duplicate movies with the same title and release year.
    __table_args__ = (
        UniqueConstraint(
            "title",
            "release_year",
            name="uq_movie_title_year",
        ),
    )

    # Primary key generated by the database.
    id: int | None = Field(
        default=None,
        primary_key=True
    )

    # Basic shared movie information.
    title: str = Field(
        max_length=150,
        index=True,
    )

    description: str | None = Field(
        default=None,
        max_length=1000,
    )

    release_year: int

    genre: str = Field(
        max_length=50,
    )