from sqlmodel import SQLModel, Field


class User(SQLModel, table=True):
    """
    Represent a registered user stored in the database.

    The model contains the user's account information,
    hashed password and authorization role.
    """

    __tablename__ = "users"

    # Primary key generated by the database.
    id: int | None = Field(
        default=None,
        primary_key=True
    )

    # Public account information.
    username: str = Field(
        max_length=100,
        index=True,
        unique=True
    )

    email: str = Field(
        max_length=300,
        index=True,
        unique=True
    )

    # Store only the hashed password, never the plain-text password.
    password_hash: str = Field(
        max_length=300
    )

    # New users receive the regular "user" role by default.
    role: str = Field(
        default="user",
        max_length=5
    )
    