from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field


class UserMovie(SQLModel, table=True):
    """
    Represent the relationship between a user and a movie.

    This model stores user-specific information such as
    movie status and personal rating.
    """

    __tablename__ = "user_movies"

    # Prevent the same user from adding the same movie more than once.
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "movie_id",
            name="uq_user_movie",
        ),
    )

    # Primary key generated by the database.
    id: int | None = Field(
        default=None,
        primary_key=True
    )

    # Foreign key referencing the user who owns this movie entry.
    user_id: int = Field(
        foreign_key="users.id",
        index=True,
    )

    # Foreign key referencing the shared movie record.
    movie_id: int = Field(
        foreign_key="movies.id",
        index=True,
    )

    # Track whether the movie is in the watchlist or has been watched.
    status: str = Field(
        default="watchlist",
        max_length=20,
    )

    # Store the user's personal rating when one is provided.
    personal_rating: float | None = Field(
        default=None
    )




    